[project]
name = "ecophil-scraper-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "pydantic-settings>=2.8.1",
    "selenium>=4.29.0",
    "uvicorn>=0.34.0",
]
